### ISSUE TITLE
how login and @PreAuthorize("isAuthenticated()") works in this application

### ISSUE THREAD

**Issue by nidhishkrishnan** [Robert-Leggett/angular_bootstrap_spring#2]
In this application all user logins through the rest service ```http://localhost:7777/api/auth/login```, and below code is the rest mapping path to /login, but I could'nt find any method implemented with the login function, but it seems somewhere else it is authenticating with the user name and password. what does this  ```@PreAuthorize("isAuthenticated()")``` doing

 can anyone please tell me what is doing behind the scene
```
 @PreAuthorize("isAuthenticated()")
    @RequestMapping(value = "/login", method = RequestMethod.POST, produces = { MediaType.APPLICATION_JSON_VALUE })
    public void login() {  }
```

**Comment by Robert-Leggett** [comment]
Based on the SecurityConfig it has been configured to allow annotation based authentication rules.

@EnableGlobalMethodSecurity(prePostEnabled = true)

That means rather then having to code the rules into the configure method in the SecurityConfig we can mark endpoints we want protected with the @PreAuthorize or @PostAuthorize annotation, if you want @Secure you will need to enable that also.

So when the @PreAuthorize annotation is detected it with check the rules defined e.g. isAuthenticated() and trigger the Spring Security Authentication process to begin, in our case it will check that a user is already authenticated or try to authenticate the user based off the through token authentication or basic authentication.

This is a stateless application so the user session is not kept and each request that has security annotation will need to Authenticate each request.  From our setup it will try to see if the user can be authenticate via a token if not then basic authentication and if it is authenticated then each response will return a token that other requests can use for authentication, otherwise a 401 is always returned.

To cut a long story short you don't need to use /api/auth/login endpoint to login, I just created it as an identifiable endpoint, as the idea was that first time login will be done via basic authentication and then all future requests will be authenticated via the token returned from the first authentication response.

Spring Security does the authentication based of our configuration not the login method.
